### ISSUE TITLE
[Bug?] Loamy dirt under dynamic trees turns to regular minecraft dirt after roots disappear, possibly the same with silt dirt

### ISSUE THREAD

**Issue by DarcClan** [the-realest-stu/Dynamic-Trees-BOP#14]
Basically the title, not sure if that's a bug that can be fixed or a unresolveable "feature".

**Comment by ferreusveritas** [comment]
The method we use does not currently store the original dirt type in the rooty dirt block. We decided it would be wasteful to use tile entities to store that data and even more wasteful to make a unique block type for each possible kind of dirt.
If we made it so that it becomes the same dirt as a neighbor then it could cause problems with unintended conversion of dirt types that other mods may not want duplicated.
For all intents and purposes it's unresolveable.
