### ISSUE TITLE
Palm seeds have a prohibitively low drop rate(extinction level event needed just to get 1 :P)

### ISSUE THREAD

**Issue by 63502** [the-realest-stu/Dynamic-Trees-BOP#8]
While love the new palm trees and how realistic the leaves are, they never actually drop palm seeds that I need to grow more with. ~~I think this may be because the new palm trees don't actually have any leaf blocks on them, and therefore no drop chance for seeds.~~ Am I missing something important about them? Do they grow coconuts or something that drops seeds like how some oaks grow apples?

**Comment by 63502** [comment]
I take back what I said above, the leaf blocks of the palm tree just have an insanely low drop rate when the tree is chopped. I just got my first palm seed after 3 survival worlds and approximately 50+ palm trees chopped. Maybe bump up the drop rate so 1-2 drop per tree chopped?

**Comment by ferreusveritas** [comment]
You're right about this.  We overlooked this problem. Dynamic trees have a slight chance to drop a seed per leaves block.  Normally there's at least 50 or so leaves blocks on a dynamic tree.  Palm trees have 10 leaves blocks so it's at least 5 times less likely to drop a seed when harvested.  This will be fixed before next release.

**Comment by ferreusveritas** [comment]
On the subject of coconuts that's a feature request that's not likely to happen since BoP does not feature coconuts and players will immediately request that they be edible. Since the dirt bucket can swap saplings for seeds(coconuts) this can break some game mechanics.  I deliberately made the seed not a coconut because if this.  However if a mod like Pam's Harvestcraft started using dynamic trees(or an add-on was made) that might be a different story.  The palm tree should still voluntarily drop it's current seeds though.

**Comment by 63502** [comment]
Ah, ok. That sounds reasonable.

**Comment by the-realest-stu** [comment]
Fixed in the latest release
